# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "Hello, Maowen!"
    silent: true
  zettel:open:
    dir: ~/workspace/maowen-archive/
    cmds:
      - nvim ./README.md
